#!/usr/bin/env python3
"""Generate wine.html -- a static status page and control panel.

Deliberately a *generated static file*, not an app. The repo is public, so
a browser page here can hold no GitHub token; anything that changes the
repo has to go through GitHub's own authenticated UI. So this page reads
config and links out to:
  - Actions "Run workflow" pages, to run the scraper or the probe
  - Issue forms, which .github/workflows/apply-config.yml turns into a PR
  - the GitHub web editor, for direct YAML edits

Regenerated by .github/workflows/dashboard.yml on every push to main.
"""
import datetime as dt
import html
import json
from pathlib import Path

import pricebook
import scraper

REPO = "philipraymondh-ctrl/launcher"
OUTPUT = Path(__file__).parent / "wine.html"

CSS = """
*{margin:0;padding:0;box-sizing:border-box}
body{background:#0d0d0f;color:#e8e8ea;font:15px/1.55 -apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;
 -webkit-font-smoothing:antialiased;padding:28px 18px 64px;max-width:940px;margin:0 auto}
h1{font-size:21px;font-weight:600;letter-spacing:-.01em}
h2{font-size:12px;font-weight:600;text-transform:uppercase;letter-spacing:.09em;
 color:#8b8b93;margin:38px 0 12px}
.sub{color:#8b8b93;font-size:13px;margin-top:5px}
.actions{display:flex;flex-wrap:wrap;gap:9px;margin-top:22px}
a.btn{display:inline-block;background:#1a1a1f;border:1px solid #2e2e36;color:#e8e8ea;
 text-decoration:none;padding:11px 15px;border-radius:9px;font-size:14px;font-weight:500}
a.btn:active{background:#26262e}
a.btn.go{background:#1d3a2a;border-color:#2c5740;color:#7ee2a8}
.cards{display:grid;grid-template-columns:repeat(auto-fit,minmax(112px,1fr));gap:9px;margin-top:18px}
.card{background:#141418;border:1px solid #24242b;border-radius:10px;padding:13px}
.card .n{font-size:23px;font-weight:600}
.card .l{font-size:11px;color:#8b8b93;text-transform:uppercase;letter-spacing:.06em;margin-top:3px}
.scroll{overflow-x:auto;-webkit-overflow-scrolling:touch}
table{border-collapse:collapse;width:100%;font-size:13.5px;min-width:460px}
th{text-align:left;font-size:11px;text-transform:uppercase;letter-spacing:.07em;color:#8b8b93;
 padding:8px 11px 8px 0;border-bottom:1px solid #24242b;font-weight:600;white-space:nowrap}
td{padding:9px 11px 9px 0;border-bottom:1px solid #1a1a1f;vertical-align:top}
tr:last-child td{border-bottom:none}
.pill{display:inline-block;font-size:11px;font-weight:600;padding:2.5px 8px;border-radius:20px;white-space:nowrap}
.ok{background:#12301f;color:#68d391}
.warn{background:#33260f;color:#e3b341}
.bad{background:#331717;color:#e37070}
.mut{background:#1f1f26;color:#8b8b93}
a.q{color:#7aa7e8;text-decoration:none}
code{font:12.5px ui-monospace,SFMono-Regular,Menlo,monospace;color:#b9b9c2}
footer{margin-top:46px;padding-top:16px;border-top:1px solid #1e1e24;color:#6e6e77;font-size:12px}
@media (prefers-color-scheme:light){
 body{background:#fbfbfc;color:#16161a}
 h2,.sub,.card .l,th{color:#6a6a74}
 a.btn{background:#fff;border-color:#dcdce3;color:#16161a}
 a.btn.go{background:#e7f7ee;border-color:#b7e3c9;color:#1a7f45}
 .card{background:#fff;border-color:#e7e7ec}
 td{border-bottom-color:#eeeef2}
 th{border-bottom-color:#dcdce3}
 code{color:#4a4a55}
 footer{border-top-color:#e7e7ec;color:#87878f}
}
"""


def esc(v):
    return html.escape(str(v))


def pill(text, kind):
    return f'<span class="pill {kind}">{esc(text)}</span>'


def collect():
    book = pricebook.load_pricebook()
    stale = {p["name"] for p in pricebook.stale_producers(book)}
    refs = {p["name"]: p for p in book.get("producers", [])}

    shops = [
        {
            "name": s["name"],
            "url": s["url"],
            "platform": s["platform"],
            "verified": bool(s.get("verified", True)),
        }
        for s in scraper.SHOPS
        if not s["name"].startswith("example-")
    ]

    producers = []
    for name, aliases in scraper.PRODUCERS.items():
        entry = refs.get(name, {})
        producers.append({
            "name": name,
            "aliases": aliases,
            "region": entry.get("region", "-"),
            "reference": entry.get("reference_750_eur"),
            "verified": bool(entry.get("verified", False)),
            "stale": name in stale,
            "in_pricebook": name in refs,
        })

    return shops, producers, book


def render(shops, producers, book):
    verified_shops = sum(s["verified"] for s in shops)
    verified_refs = sum(p["verified"] for p in producers)
    defaults = book.get("defaults", {})

    actions = "".join([
        f'<a class="btn go" href="https://github.com/{REPO}/actions/workflows/scraper.yml">Run scraper</a>',
        f'<a class="btn" href="https://github.com/{REPO}/actions/workflows/probe.yml">Run shop probe</a>',
        f'<a class="btn" href="https://github.com/{REPO}/issues/new?template=add-producer.yml">+ Producer</a>',
        f'<a class="btn" href="https://github.com/{REPO}/issues/new?template=add-shop.yml">+ Shop</a>',
        f'<a class="btn" href="https://github.com/{REPO}/edit/main/prices.yaml">Edit prices</a>',
        f'<a class="btn" href="https://github.com/{REPO}/actions">All runs</a>',
    ])

    cards = "".join([
        f'<div class="card"><div class="n">{verified_shops}/{len(shops)}</div><div class="l">Shops live</div></div>',
        f'<div class="card"><div class="n">{verified_refs}/{len(producers)}</div><div class="l">Prices verified</div></div>',
        f'<div class="card"><div class="n">{len(producers)}</div><div class="l">Producers</div></div>',
        f'<div class="card"><div class="n">{defaults.get("deal_threshold", "-")}</div><div class="l">Deal at</div></div>',
        f'<div class="card"><div class="n">{defaults.get("fair_ceiling", "-")}</div><div class="l">High above</div></div>',
    ])

    prows = ""
    for p in sorted(producers, key=lambda x: x["name"]):
        if not p["in_pricebook"]:
            status = pill("no entry", "bad")
        elif p["verified"] and not p["stale"]:
            status = pill("verified", "ok")
        else:
            status = pill("unverified", "warn")
        ref = f'€{p["reference"]}' if p["reference"] is not None else "—"
        prows += (
            f'<tr><td><b>{esc(p["name"])}</b><br><code>{esc(", ".join(p["aliases"]))}</code></td>'
            f'<td>{esc(p["region"])}</td><td>{ref}</td><td>{status}</td></tr>'
        )

    srows = ""
    for s in sorted(shops, key=lambda x: (not x["verified"], x["name"])):
        status = pill("live", "ok") if s["verified"] else pill("not live", "mut")
        plat = {"shopify": "ok", "woocommerce": "ok", "html": "warn"}.get(s["platform"], "mut")
        srows += (
            f'<tr><td><a class="q" href="{esc(s["url"])}">{esc(s["name"])}</a></td>'
            f'<td>{pill(s["platform"], plat)}</td><td>{status}</td></tr>'
        )

    live_note = (
        "No shop is live yet — every entry is still <code>verified: false</code>, so runs "
        "deliberately fetch nothing. Platforms shown below are confirmed by the probe; the "
        "fixtures behind them are still placeholders."
        if verified_shops == 0 else
        f"{verified_shops} shop(s) are live and will be fetched on the hourly run."
    )

    generated = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d %H:%M UTC")

    return f"""<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
<meta name="theme-color" content="#0d0d0f">
<title>Wine tracker</title>
<style>{CSS}</style>
</head><body>

<h1>Wine tracker</h1>
<div class="sub">Monitoring {len(shops)} French/EU natural wine shops for {len(producers)} producers.
Hourly, {esc(defaults.get("deal_threshold", "?"))}× reference flags a deal.</div>

<div class="actions">{actions}</div>
<div class="cards">{cards}</div>

<h2>Producers &amp; reference prices</h2>
<div class="scroll"><table>
<thead><tr><th>Producer / aliases</th><th>Region</th><th>Ref 750ml</th><th>Price data</th></tr></thead>
<tbody>{prows}</tbody></table></div>
<div class="sub" style="margin-top:11px">Unverified references are best-guess placeholders.
Fill real figures into <code>prices.yaml</code> manually, then set <code>verified: true</code> —
nothing here fetches Wine-Searcher.</div>

<h2>Shops</h2>
<div class="sub" style="margin:-4px 0 12px">{live_note}</div>
<div class="scroll"><table>
<thead><tr><th>Shop</th><th>Platform</th><th>Status</th></tr></thead>
<tbody>{srows}</tbody></table></div>

<footer>
Generated {generated} from <code>scraper.py</code> and <code>prices.yaml</code>.
Regenerates on every push to <code>main</code>. Buttons open GitHub, which handles sign-in —
this page holds no credentials.
</footer>

</body></html>
"""


def main():
    shops, producers, book = collect()
    OUTPUT.write_text(render(shops, producers, book))
    print(f"Wrote {OUTPUT} ({OUTPUT.stat().st_size} bytes)")
    print(f"  {len(shops)} shops, {len(producers)} producers")


if __name__ == "__main__":
    main()
